CREATE TABLE `positions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ticker_id` int(11) DEFAULT NULL,
  `ettime` datetime DEFAULT NULL,
  `etprice` float DEFAULT NULL,
  `etival` float DEFAULT NULL,
  `xttime` datetime DEFAULT NULL,
  `xtprice` float DEFAULT NULL,
  `xtival` float DEFAULT NULL,
  `entry_date` datetime  DEFAULT NULL,
  `entry_price` float DEFAULT NULL,
  `entry_ival` float DEFAULT NULL,
  `exit_date` datetime DEFAULT NULL,
  `exit_price` float DEFAULT NULL,
  `exit_ival` float DEFAULT NULL,
  `days_held` int(11) DEFAULT NULL,
  `nreturn` float DEFAULT NULL,
  `logr` float DEFAULT NULL,
  `short` tinyint(1) DEFAULT NULL,
  `closed` tinyint(1) DEFAULT NULL,
  `entry_pass` int(11) DEFAULT NULL,
  `roi` float DEFAULT NULL,
  `num_shares` int(11) DEFAULT NULL,
  `etind_id` int(11) DEFAULT NULL,
  `xtind_id` int(11) DEFAULT NULL,
  `scan_id` int(11) DEFAULT NULL,
  `consumed_margin` float DEFAULT NULL,
  `eind_id` int(11) DEFAULT NULL,
  `xind_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY index_ticker_id_entry_date_eind (`ticker_id`,`entry_date`, `eind_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ;