#!/usr/bin/env ruby

require 'optparse'
options = {}
optparse = OptionParser.new do |opts|
  opts.banner = "Usage backtest [options]"
  options[:parallel] = 1

  opts.on('-c', '--config FILE', "The Backtest config file") do |config|
    options[:config] = config
  end

  opts.on('-p', '--parallel NUMBER', "Parallelize NUMBER of processe") do |p|
    options[:parallel] = p.to_i
  end

  opts.on('-h', '--help', 'Display this screen') do
    puts opts
    exit
  end
end

optparse.parse!
puts "Running #{options[:parallel]} processes"
options[:parallel].times do |proc_id|
  puts "nice rake active_trader:backtest CONFIG=#{options[:config]} PROC_ID=#{proc_id} PROC_CNT=#{options[:parallel]} &"
  system "nice rake active_trader:backtest CONFIG=#{options[:config]} PROC_ID=#{proc_id} PROC_CNT=#{options[:parallel]} &"
end

# Local Variables:
# mode:ruby
# End:
