#!/usr/bin/env ruby
# Copyright © Kevin P. Nolan 2009 All Rights Reserved.

require 'rubygems'
require 'optparse'
require 'ostruct'
require 'daemons'

root_path_ary = File.expand_path(File.dirname(__FILE__)).split('/') + ['..']
root_dir = File.expand_path(File.join(root_path_ary))
require File.join(root_dir,'config/mini-environment')


dd_index = ARGV.index('--')
my_options = dd_index ? ARGV[dd_index+1..-1] : []       # Extract options after --
daemon_opts = ARGV[0..(dd_index ? dd_index-1 : -1)]     # Extract options before -- or EOS

options = OpenStruct.new
optparse = OptionParser.new do |opts|
  opts.default_argv = my_options
  opts.banner = "Usage task_manager daemon_args -- options"

  opts.on('-C', '--config FILE', String, "The task config file") do |config_file|
    options.config_file = config_file
  end

  options.server_count = 1
  opts.on('-s', '--servers NUMBER', Integer, "Fork NUMBER of task servers") do |s|
    options.server_count = s
  end

  opts.on('-h', '--help', 'Display this screen') do
    puts opts
  end
end

optparse.parse!

# Don't bother parsing task_manager specific options (ones after  --) if help or version number only requested for Daemons
if daemon_opts.find_index { |el| el == '-h' || el == '--help' || el == '--version' }
  Daemons.run_proc('task_manager', { })
elsif daemon_opts.index { |el| el == 'start' || el == 'run' } && options.config_file.blank?
  puts 'config file is MANDITORY!'
else
  daemon_options = {
    :dir_mode => :normal,
    :dir => File.join(root_dir, 'pids'),
    :multiple => false,
    :ontop => options.server_count.zero?,
    :backtrace => true,
    :log_output => true
  }
  server_count = options.server_count
  server_count = 1 if options.server_count.zero?
  Daemons.run_proc('task_manager', daemon_options) do
    loop {
      puts 'running...'
      sleep(5)
    }
    #Task::Base.run(config_file, server_count)
  end
end

# Local Variables:
# mode:ruby
# End:
